SET IDENTITY_INSERT [dbo].[Stats] ON
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (1, N'Points de Vie')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (2, N'PA')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (3, N'PM')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (4, N'PW') 
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (5, N'Maîtrise Élémentaire')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (6, N'Maîtrise sur 3 éléments aléatoires')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (7, N'Maîtrise sur 2 éléments aléatoires')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (8, N'Maîtrise sur 1 élément aléatoire')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (9, N'Maîtrise Feu')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (10, N'Maîtrise Eau')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (11, N'Maîtrise Terre')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (12, N'Maîtrise Air')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (13, N'Maîtrise Mêlée')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (14, N'Maîtrise Distance')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (15, N'Maîtrise Monocible')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (16, N'Maîtrise Zone')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (17, N'Maîtrise Critique')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (18, N'Maîtrise Dos')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (19, N'Maîtrise Soin')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (20, N'Maîtrise Berserk')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (21, N'Résistance Élémentaire')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (22, N'Résistance sur 3 éléments aléatoires')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (23, N'Résistance sur 2 éléments aléatoires')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (24, N'Résistance sur 1 élément aléatoire')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (25, N'Résistance Feu')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (26, N'Résistance Eau')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (27, N'Résistance Terre')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (28, N'Résistance Air')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (29, N'Résistance Critique')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (30, N'Résistance Dos')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (31, N'Coup Critique')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (32, N'Parade')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (33, N'Initiative')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (34, N'Portée')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (35, N'Esquive')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (36, N'Tacle')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (37, N'Sagesse')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (38, N'Prospection')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (39, N'Contrôle')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (40, N'Art du Barda')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (41, N'Volonté')

INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (190, N'Point de Vie') -- correspond aux Points de vie (id 1)
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (167, N'PM max') -- correspond aux PM (id 3)
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (147, N'PW max') -- correspond aux PW (id 4)
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (127, N'Transfert Tellurique (Niv.10)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (128, N'Rage (+35 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (129, N'Rage (+30 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (130, N'Vivacité 90% (+24 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (134, N'Berserk 75% (+20 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (135, N'Berserk 50% (+12 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (136, N'Requinquage 75% (+2 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (137, N'Requinquage 50% (+2 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (138, N'Requinquage 25% (+4 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (139, N'Fortification (+35 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (140, N'Muraille 75% (+20 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (141, N'Muraille 50% (+12 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (142, N'Fortification (+30 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (143, N'Niv. aux sorts élémentaires')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (144, N'Berserk 75% (+15 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (145, N'Berserk 50% (+9 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (146, N'Vivacité 90% (+16 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (148, N'Vivacité 90% (+20 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (149, N'Fortification (+25 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (150, N'Fortification (+20 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (151, N'Vivacité 90% (+12 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (154, N'Requinquage 66% (+3 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (155, N'Requinquage 33% (+3 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (156, N'Muraille 75% (+10 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (157, N'Rage (+20 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (160, N'Niv. aux sorts Terre')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (162, N'Etoi Eskeutula (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (163, N'PdV') -- correspond aux dégâts infligés par les armes
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (164, N'533 Points de Vie') -- correspond à une partie des hp du rod gerse
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (165, N'Soigne 42 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (166, N'Soigne 56 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (168, N'Soigne 39 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (169, N'1 PA') -- correspond au gain de pa de l'aiguille d'outre-temps
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (170, N'Soigne 62 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (171, N'Soigne 33 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (172, N'Soigne 38 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (173, N'Soigne 50 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (174, N'Soigne 44 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (175, N'Soigne 48 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (176, N'Soigne 70 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (177, N'Soigne 24 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (178, N'PM (1 tour) (non-cumulable)') -- correspond au gain de pm de la claymore de fhenris
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (179, N'PdV et en vole 100') -- correspond au vol de vie de la sanguinaire (100 = 100%)
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (180, N'Maîtrise CMC')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (181, N'Soigne 22 PdV')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (182, N'Niv. aux sorts Air')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (183, N'Niv. aux sorts Eau')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (184, N'9 Maîtrise CMC')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (185, N'15 Esquive') -- correspond à une partie de l'esquive de l'arc de moelle
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (186, N'Quantité Récolte en Forestier')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (187, N'aux dégâts contre les Tofus')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (188, N'aux dégâts contre les Bouftous')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (189, N'PdV Terre')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (191, N'Emblème du Zobal (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (192, N'Emblème du Xelor (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (193, N'Emblème du Steamer (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (194, N'Emblème du Sram (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (195, N'Emblème du Sadida (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (196, N'Emblème du Sacrieur (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (197, N'Emblème du Roublard (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (198, N'Emblème du Pandawa (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (199, N'Emblème du Iop (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (200, N'Emblème du Feca (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (201, N'Emblème du Cra (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (202, N'Emblème d''Osamodas (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (203, N'Emblème d''Enutrof (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (204, N'Emblème d''Eniripsa (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (205, N'Emblème d''Ecaflip (Niv.1)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (206, N'Dofus Prismatique (+1 Niv.)')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (207, N'Résistance Élémentaire bien méritée')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (208, N'Quantité Récolte en Herboriste')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (209, N'Quantité Récolte en Mineur')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (210, N'Quantité Récolte en Paysan')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (211, N'Quantité Récolte en Trappeur')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (212, N'Quantité Récolte en Pêcheur')
INSERT INTO [dbo].[Stats] ([Id], [type]) VALUES (213, N'de vitesse de déplacement')
SET IDENTITY_INSERT [dbo].[Stats] OFF
